<a href="https://colab.research.google.com/github/ShauryaPrakashVerma/Machine_Learning_Practice/blob/main/17_excel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
pd.read_excel('Habit_Tracker.xlsm')

/usr/local/lib/python3.12/dist-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
/usr/local/lib/python3.12/dist-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)

,DAY,DATE,DAILY TASKS,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,PROGRESS BAR
0,NaN,NaT,Drink Water 4,Github,Python,Practice Comm,Leetcode,Creative,Extra,NaN
1,Monday,2026-05-28,1,2,1,0,0,1,1,0.666667
2,Tuesday,2026-05-29,-1,-1,-1,-1,-1,-1,-1,0.000000
3,Wednesday,2026-05-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
4,Thursday,2026-05-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
...,...,...,...,...,...,...,...,...,...,...
94,Wednesday,2026-08-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
95,Thursday,2026-08-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
96,Friday,2026-08-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
97,Saturday,2026-09-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
98,Sunday,2026-09-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000

In [3]:
pd.read_excel('Habit_Tracker.xlsm', index_col="DAY")

/usr/local/lib/python3.12/dist-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
/usr/local/lib/python3.12/dist-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)

,DATE,DAILY TASKS,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,PROGRESS BAR
DAY,,,,,,,,,
NaN,NaT,Drink Water 4,Github,Python,Practice Comm,Leetcode,Creative,Extra,NaN
Monday,2026-05-28,1,2,1,0,0,1,1,0.666667
Tuesday,2026-05-29,-1,-1,-1,-1,-1,-1,-1,0.000000
Wednesday,2026-05-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
Thursday,2026-05-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
...,...,...,...,...,...,...,...,...,...
Wednesday,2026-08-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
Thursday,2026-08-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
Friday,2026-08-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
Saturday,2026-09-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
Sunday,2026-09-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000

In [7]:
# suppose we want another sheet in the excel file
pd.read_excel("Habit_Tracker.xlsm", sheet_name='Sheet1')

/usr/local/lib/python3.12/dist-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
/usr/local/lib/python3.12/dist-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)

,DAY,DATE,DAILY TASKS,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,PROGRESS BAR
0,NaN,NaT,Drink Water 4,Github,Python,Practice Comm,Leetcode,Creative,Extra,NaN
1,Monday,2026-05-28,1,2,1,0,0,1,1,0.666667
2,Tuesday,2026-05-29,-1,-1,-1,-1,-1,-1,-1,0.000000
3,Wednesday,2026-05-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
4,Thursday,2026-05-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
...,...,...,...,...,...,...,...,...,...,...
94,Wednesday,2026-08-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
95,Thursday,2026-08-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
96,Friday,2026-08-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
97,Saturday,2026-09-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
98,Sunday,2026-09-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000

# Reading Text files

In [8]:
# first recognize how the data in the text file is arranged
# eventually we will use the read_csv functions

In [ ]:
pd.read_csv('questions_answer.txt', sep='\t')